### ISSUE TITLE
Translations not assigned correctly to the newly created localization key

### ISSUE THREAD

**Issue by albertoponcato** [nittin-cz/xperience-community-localization#14]
**Description:**
I'm experiencing an issue when creating a new localization key in Xperience by Kentico (version 29.5.3, but also noticed in previous versions).

**Steps to reproduce:**
1. Create a new localization key.
2. Populate the translations for different languages.
3. Click the save button.

**Expected behavior:**
The localization key should be saved with the corresponding translations, and upon reopening the key, all translations should be visible and assigned correctly.

**Actual behavior:**
The localization key is created correctly, but the translations are not assigned to the key. When I reopen the newly created key, the translations are missing. However, if I manually insert the translations again, they are saved and displayed correctly.

**Version:**
Xperience by Kentico 29.5.3 (also noticed in previous versions)

**Comment by bkapustik** [comment]
Thank you for bringing this to our attention. We will investigate and keep you informed of our progress.

**Comment by bkapustik** [comment]
Hello, we have found the issue and the fix should be added tomorrow (18.10.2024) together with update to the newest version of XbyK libraries 29.6.0.

**Comment by albertoponcato** [comment]
Thank you for the update, this is great news! Looking forward to the fix and the new version of the XbyK libraries. Much appreciated!

**Comment by bkapustik** [comment]
Hello, this issue should be solved in the latest Localization NuGet package [1.4.1](https://www.nuget.org/packages/XperienceCommunity.Localization/1.4.1)
